### ISSUE TITLE
Drawing is laggy on iOS 11. Have not tested in iOS 10.

### ISSUE THREAD

**Issue by talkaboutdesign** [joehour/ScratchCard#11]

**Comment by PatrickAdams** [comment]
@talkaboutdesign did you ever solve this? I am having the same issue.

**Comment by PatrickAdams** [comment]
@joehour have you tested this on a device? Runs perfectly fine on the computer in simulator but is laggy on an actual device.

**Comment by joehour** [comment]
@PatrickAdams  before iOS 10, it work fine on device. 
I will try to solve this issue.

**Comment by PatrickAdams** [comment]
@joehour any progress on this? I have a week to finish what I am working on an am relying heavily on this library. If it can't be fixed that quick then I am going to have to look into alternatives or create my own.

**Comment by joehour** [comment]
@PatrickAdams 
I've already been solved this issue~
You can find code in master branch, or update it by CocoaPods(ver 1.1.1)~

**Comment by PatrickAdams** [comment]
Wow, works great @joehour, so smoooooth 👍 Thank you!

**Comment by dilipiOSDeveloper** [comment]
> @PatrickAdams I've already been solved this issue~ You can find code in master branch, or update it by CocoaPods(ver 1.1.1)~

Can you pls tell what are the changes done for lagging because still its lagging i have not used pod i have only used classes for ScratchCard
