### ISSUE TITLE
Programmatically finish the scratching?

### ISSUE THREAD

**Issue by Azlond** [joehour/ScratchCard#12]
Hi Joe,

first of all, thanks for your work. This library has already been a huge help.
I'm relatively new to iOS development/Swift, so I'm still trying to find my way around. 
Is it possible to finish the scratching programmatically? As in, don't have it disappear all at once as with `scratchCard.scratchView.isHidden = true`, but have a scratching animation that clears it for you?

Hope you had a good weekend!
Thanks,
Jan

**Comment by joehour** [comment]
Hi, Jan
Here's an example:
```
    //Scratch Moved Event(optional)
    func scratchMoved(_ view: ScratchUIView) {
        let scratchPercent: Double = scratchCard.getScratchPercent()
        if scratchPercent > 0.5 {
            UIView.animate(
                // your effect
                ,
                completion: { finished in
                    scratchCard.scratchView.isHidden = true
            }
            )
        }
    }
```
Best Regards
Joe

**Comment by Azlond** [comment]
Hi Joe,
thanks for your answer. I don't think using UIView.animate helps me, as that wouldn't give me access to ScratchUIView-functions, which I think I need to use to draw the alpha-line on the mask-image.

What I've done now instead is create a new 
`open func autoScratch(){}`
function in _ScratchUIView_, which iterates over the screen-width/height and calls `scratchView.renderLineFromPoint(start, end: end)` with the screen coordinates.

It's not exactly running smoothly, but it's definitely close to what I want, so I'll try to this some more work to improve it.

Jan
