### ISSUE TITLE
Scratching crashes since iOS 11.2/Xcode 9.2 / nil while unwrapping an Optional 

### ISSUE THREAD

**Issue by Azlond** [joehour/ScratchCard#13]
In `ScratchView.swift / getAlphaPixelPercent() -> Double`, `let pixelData = provider.data` has started crashing since updating to iOS 11.2 on my iPhone. Since I updated to Xcode 9.2, it also crashes in the simulator.
`Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value`
This also happens with your example project.

Update: Simply tapping does clear the tapped part, but a moving TouchEvent crashes the app. [Image](https://i.imgur.com/70C3YEh.png)

**Comment by joehour** [comment]
Hi,
I think it's a CGDataProvider issue on iOS 11.2. (it work fine on older version~)
So, I change getAlphaPixelPercent method to avoid this issue.
You can find code in master branch, or update it by CocoaPods(ver 1.1.2)~

**Comment by Azlond** [comment]
This has fixed the crashing, thanks! 
However, I've encountered a new problem. I'll open up a new issue for it.
