### ISSUE TITLE
Crashing at iOS 11.2 

### ISSUE THREAD

**Issue by jjangir610** [joehour/ScratchCard#19]
It's crashing on ios 11.2, and also crashing the OS as well.

**Comment by joehour** [comment]
Hi,
It work fine on iOS11.2/Xcode9.2 ~
Please check this thread([Issue#13](https://github.com/joehour/ScratchCard/issues/13))~

**Comment by jjangir610** [comment]
Already saw that but it was not working for me. Now I fixed crash by replacing  CGColorSpaceCreateDeviceRGB() to CGColorSpaceCreateDeviceGray() in processPixels(image: UIImage) -> UIImage?

Is there any specific reason for using CGColorSpaceCreateDeviceRGB() ?

**Comment by joehour** [comment]
Hi,
[processPixels](https://github.com/joehour/ScratchCard/blob/master/ScratchCard/ScratchView.swift#L219) is to avoid the pixel data of alpha channel is 0 ~
So the image colorspace is RGBA not Grayscale ~

Theoretically, if [processPixels](https://github.com/joehour/ScratchCard/blob/master/ScratchCard/ScratchView.swift#L219) fail it will load image by [default way](https://github.com/joehour/ScratchCard/blob/master/ScratchCard/ScratchView.swift#L60)
In your case, i think you can skip the [processPixels](https://github.com/joehour/ScratchCard/blob/master/ScratchCard/ScratchView.swift#L219) function

**Comment by sonic009** [comment]
It is lagging on vertically downward erase.
