### ISSUE TITLE
Adding label inside the scratch pad

### ISSUE THREAD

**Issue by zumrywahid** [joehour/ScratchCard#20]
Hi,

I want to add ui label between mask image and coupon image.   currently if i tried to add , the label text is visible on top of scratch pad .

Requirement is , i want to type some text in the coupon programatically. it should be visible when use tries to scratch. 

Regards,

**Comment by joehour** [comment]
Hi,
You need to add the text ui in the [contentLayer(ScratchView.swift)](https://github.com/joehour/ScratchCard/blob/dd5c34c8ee3214e7d1cfaae146d12ced602932a3/ScratchCard/ScratchView.swift#L93)

Here's an example:
```
var text = UITextField()
text.frame = CGRect(x:0, y:0, width:width, height:height)
text.text = "test message"
contentLayer.addSublayer(text.layer)
```
Best Regards
Joe

**Comment by tusharuit25** [comment]
I seen you answered very well I have humble request will you please extend this library for both text and image ? It will be very useful...
