### ISSUE TITLE
Load coupon and mask image from url

### ISSUE THREAD

**Issue by Zorkham** [joehour/ScratchCard#4]
Hello,

Is it possible to load coupon and mask image from url in additional of local images ?

Thanks, Cédric

**Comment by joehour** [comment]
ScratchCard doesn't support url image~ 
You can use NSURLSession to download image form url first, then create the ScratchView.

**Comment by Zorkham** [comment]
Hello Joe,

Thanks for your quick response!
I am trying to implement your solution but i encounter difficulties,
did you have an example by chance of this functionality?

Thanks, Cédric

**Comment by joehour** [comment]
Hi,
If you have problem with download image,
you can refer to the [SDWebImage](https://github.com/rs/SDWebImage) library.

Besides, I think this [Stackoverflow thread](http://stackoverflow.com/questions/26285808/how-to-save-a-remote-image-with-swift) can help you~

**Comment by Zorkham** [comment]
Hello Joe,

Sorry, I don't specify that my problem comes from the fact that "ScratchUIView" is waiting for "String" types for "Coupon" and "MaskImage". To resolve my problem i need to modify your library is not it ?

Thanks, Cédric

**Comment by joehour** [comment]
Hi,
First,  ScratchCard library load the [coupon image](https://github.com/joehour/ScratchCard/blob/swift3.0/ScratchCard/ScratchUIView.swift#L50)  from main cache.
So, "Coupon" and "MaskImage" is the file name(string type) from main cache.

For your issue, 

you can download image to cache first, then use the ScratchCard library without modify.
But, for the memory issue, change [UIImage(named:coupon)](https://github.com/joehour/ScratchCard/blob/swift3.0/ScratchCard/ScratchUIView.swift#L50) to UIImage(contentsOfFile: imagePath) is a better way~

Or you can modify the ScratchCard library like this in [ScratchUIView](https://github.com/joehour/ScratchCard/blob/swift3.0/ScratchCard/ScratchUIView.swift#L50). (load UIImage from url)
```
//coupon is your image url string
let data = try Data(contentsOf: URL(string: coupon)!)
couponImage = UIImageView(image:UIImage(data: data))
```
For UI experiences, asynchronously loading is a better way, you can refer to the[ SDWebImage](https://github.com/rs/SDWebImage) library~

In the same way as [mask image](https://github.com/joehour/ScratchCard/blob/swift3.0/ScratchCard/ScratchView.swift#L53)~

**Comment by Zorkham** [comment]
Hello Joe,

Thank you for all your answers and perfect details about my problem, I finally changed "Coupon" and "MaskImage" to "Data" types in the library and helped with the StackOverflow thread that you recommend me, it works now!

Thanks again, Cédric

**Comment by Kida007** [comment]
Hey  @joehour, Im new to swift  . I was trying to do it with SDWebImage . but i cant how to download it and store it static image fashion , and then pass a "name string" of that image to Scratch Card . 

All the tuts , they directly assign it to UIImage. can you explain a bit about async solution.

Thanks

**Comment by joehour** [comment]
Hi, @Kida007 

you can find answer in previous reply~ 
[download image with asynchronously](https://github.com/joehour/ScratchCard/issues/4#issuecomment-277421417)
[modify the ScratchCard library](https://github.com/joehour/ScratchCard/issues/4#issuecomment-277815688)

Best Regards
