### ISSUE TITLE
Coupon image is not visible

### ISSUE THREAD

**Issue by kwolniak** [joehour/ScratchCard#5]
I run example project and it works but when I scratch the Mask image I don't see Coupon image below. Instead of I see background of Main.storyboard View.

I run this example on iPhone SE with iOS 10.2.1. 
It's the same behavior on simulator (Xcode 8.2.1).

**Comment by joehour** [comment]
Hi,

Please add the attached file name to resolve this issue~
Here's an example:

[`scratchCard = ScratchUIView(frame: CGRect(x:50, y:80, width:320, height:480), Coupon: "image.jpg", MaskImage: "mask.png", ScratchWidth: CGFloat(40))`](https://github.com/joehour/ScratchCard/blob/swift3.0/Example/Example/ViewController.swift#L20)

**Comment by kwolniak** [comment]
yep it works, thx.
