### ISSUE TITLE
Cannot scratch in iPhone7

### ISSUE THREAD

**Issue by uronly14me** [joehour/ScratchCard#7]
ScratchCard is not scratched at iPhone7.
How do I fix  this?

**Comment by joehour** [comment]
Any error log? Please describe your problem more clearly.
It work fine in simulator device

**Comment by borgeser** [comment]
Same for me. The problem is only on device iPhone 7.
I think the problem is related with this : http://stackoverflow.com/questions/41151557/xcode-8-coregraphics-issue-with-iphone-7-running-ios-10 
i.e. the alpha channel is not well interpreted when masking the image.

**Comment by uronly14me** [comment]
@joehour 
Thank you owner for your quick reply. Yes, I find that simulator is OK too. But in real device something does not work well. And there is not any logged error.
If I see the masking image and try to scratch, it is not scratched out. But the events like  touchesBegan and method like getAlphaPixelPercent work well.

**Comment by joehour** [comment]
Unfortunately, i don't have iPhone7 device to find this problem~
Maybe it's a CoreGraphics issue.
So, I change mask method and mask image colorspace.
You can find code in [iPhone7_test](https://github.com/joehour/ScratchCard/tree/iPhone7_test)  branch~

**Comment by mikelindelsee** [comment]
I ran into the same problem and can confirm that using the iPhone7_test branch solves the problem.  Any chance of getting it merged into master/swift3.0?

Btw, thanks for the work on this!

**Comment by joehour** [comment]
Thank you for your report~
I've already been merged it into master/swift3.0
