### ISSUE TITLE
Automatically open after given percentage reached.

### ISSUE THREAD

**Issue by xpdavidx** [joehour/ScratchCard#8]
Could you please add functionality that after reaching e.g. 70% it will open the whole image.

**Comment by joehour** [comment]
Hi,

Here's an example: 
 
    //Scratch Moved Event(optional)
    func scratchMoved(_ view: ScratchUIView) {
        let scratchPercent: Double = scratchCard.getScratchPercent()
        if scratchPercent > 0.7 {
            scratchCard.scratchView.isHidden = true
        }
    }
(it works on 1.0.12 version)

**Comment by xpdavidx** [comment]
Hi,

that's nice, but it's not released yet, yes?

And thanks for quick answer.

**Comment by joehour** [comment]
Hi, 
I've already been released it
You can use it in master branch~

**Comment by xpdavidx** [comment]
pod install (without specifying version in Podfile) brings 1.0.11. Could you please check, if 1.0.12 is released successfully?

**Comment by joehour** [comment]
Hi,
It works now~

**Comment by xpdavidx** [comment]
Now it worked, thx a lot
