### ISSUE TITLE
Mask image is transparent.

### ISSUE THREAD

**Issue by xpdavidx** [joehour/ScratchCard#9]
Hi, could you please help me to find out the reason, why mask image is transparent.

Here is the code of usage:
` self.scratchCardView = ScratchUIView(frame: CGRect(x:20, y:90, width:self.bounds.width - 40, height:200), Coupon: "nowinScratch", MaskImage: "mask", ScratchWidth: CGFloat(30))
        self.scratchCardView?.delegate = self
        self.addSubview(self.scratchCardView!)`

And please find attached images that I used and the vide how it looks for me. ("mask"  image is the same image from example project)

![nowin](https://user-images.githubusercontent.com/3208327/29390489-f5a5599a-82f0-11e7-8747-a549343a3fa9.jpg)
[transparentcy.bug.mov.zip](https://github.com/joehour/ScratchCard/files/1229797/transparentcy.bug.mov.zip)

P.S. I'm using 1.0.13 version, and tried on iPhone 6s and 7 Plus, iOS 10

And let me know if you need some more infor, thanks in advance.

**Comment by xpdavidx** [comment]
Actually after some tries I found what were the issues. At first it's not working on simulator, on real device it was fine. And second, images should not be in assets. But I would like to see what you think about above mentioned problems. Thanks...

**Comment by joehour** [comment]
Hi, 
Maybe the colorspace(RGBA) of masklayer contents dosen’t work on simulator device.
So, I change the colorspace(RGBA) to Gray color space.
It will work fine on simulator & real device.
You can find code in [issue9](https://github.com/joehour/ScratchCard/tree/issue9) branch~

**Comment by xpdavidx** [comment]
at the moment it's fine for me, as I'm still able to work with real device. But when are you going to release that issue9? 

Thanks for quick response.

**Comment by joehour** [comment]
Hi,
I've already been released it(1.0.14).

**Comment by xpdavidx** [comment]
Tested with 1.0.14 but it was not fix for simulator, but in real device it works perfect.

**Comment by joehour** [comment]
Hi,
I think it's an mask initialization error on simulator device. (pixel data != 0) 
I've already been fixed and released it(1.0.15).
